# Project 6 -- Vinay Gannamaneni

**TA Help:** (for instance) John Smith, Alice Jones, etc., list names of any TAs who helped you

- For example: Help with figuring out how to write a function (describe the tasks that they helped you with)

**Collaboration:** My Friend in CS, My Uncle, Another Student, etc., list names of any other people who helped you

(describe the tasks that they helped you with)
- For example: helped figuring out how to load the dataset.
- Another example: helped debug error with my plot.

**Internet Resources:** Stack Exchange, Stack Overflow, etc.

(describe any information that you learned from internet resources, including the URLs)
- data frames in Pandas versus R from StackOverflow  https://stackoverflow.com/questions/8991709/why-were-pandas-merges-in-python-faster-than-data-table-merges-in-r-in-2012

**ChatGPT, Gemini, Claude, etc:** Any language models or generative AI chatbots that helped you.

(if you used any such tools, please tell us here)
- For example:  I asked ChatGPT how to define a new data frames
- Another example:  Gemini told me how to make a function for sorting my data

- ***Link to AI Chat History***: Please share a link to your chat if you used AI (ex. ChatGPT Shared Links)
**OVERALL MESSAGE:** Any time that you used anything except your brain to solve the questions in these projects, you need to disclose such resources at the start of the project, with details about your usage of the tools.

**YOUR OWN WORK:** Even when you utilize other resources, do NOT just copy and paste.  Write all explanations in your own words, using several sentences in English, which are understandable and which you wrote (and did not just copy and paste).

## If/else logic: mapping lightsaber color to Jedi role

In [7]:
color <- "green"

if (color == "green") {
  print("Jedi Consular")   # Green corresponds to Jedi Consular
} else if (color == "blue") {
  print("Jedi Guardian")   # Blue corresponds to Jedi Guardian
} else if (color == "purple") {
  print("Unique Balance")  # Purple corresponds to Unique Balance
} else if (color == "red") {
  print("Sith Lord")       # Red corresponds to Sith Lord
} else {
  print("Rare Occurrence") # Any other color is Rare Occurrence
}

[1] "Jedi Consular"

In [10]:
color <- "red"

if (color == "green") {
  print("Jedi Consular")   # Green corresponds to Jedi Consular
} else if (color == "blue") {
  print("Jedi Guardian")   # Blue corresponds to Jedi Guardian
} else if (color == "purple") {
  print("Unique Balance")  # Purple corresponds to Unique Balance
} else if (color == "red") {
  print("Sith Lord")       # Red corresponds to Sith Lord
} else {
  print("Rare Occurrence") # Any other color is Rare Occurrence
}

[1] "Sith Lord"

In [11]:
color <- "yellow"

if (color == "green") {
  print("Jedi Consular")   # Green corresponds to Jedi Consular
} else if (color == "blue") {
  print("Jedi Guardian")   # Blue corresponds to Jedi Guardian
} else if (color == "purple") {
  print("Unique Balance")  # Purple corresponds to Unique Balance
} else if (color == "red") {
  print("Sith Lord")       # Red corresponds to Sith Lord
} else {
  print("Rare Occurrence") # Any other color is Rare Occurrence
}

[1] "Rare Occurrence"

Assign a color first, then use if/else chain to classify the laightsaber color

In [12]:
colors <- c("green", "blue", "red", "yellow", "blue", "red", "purple", "green", "red", "blue", "red", "blue")

roles <- ifelse(colors == "green", "Jedi Consular",
         ifelse(colors == "blue", "Jedi Guardian",
         ifelse(colors == "purple", "Unique Balance",
         ifelse(colors == "red", "Sith Lord", "Rare Occurrence"))))

print(roles)

 [1] "Jedi Consular"   "Jedi Guardian"   "Sith Lord"       "Rare Occurrence"
 [5] "Jedi Guardian"   "Sith Lord"       "Unique Balance"  "Jedi Consular"
 [9] "Sith Lord"       "Jedi Guardian"   "Sith Lord"       "Jedi Guardian"

Use nested ifelse to classify each color in the vector

**Differences between if/else and ifelse:**
1. Scope:
- if/else handles a single value or condition at a time.
- ifelse is vectorized and can handle an entire vector at once.

2. Output:
- if/else executes code blocks but doesn't directly return a vector.
- ifelse returns a vector with a result for each input element.

3. Usage:
- Use if/else for single decisions or inside loops.
- Use ifelse for quick classification or transformation of vectors without loops.

## Vectorized conditional labeling of social media usage vs. sleep

In [15]:
myDF <- read.csv("/anvil/projects/tdm/data/social_media_addiction/social_media.csv")
dim(myDF)
head(myDF)

[1] 705  13

  Student_ID Age Gender Academic_Level Country    Avg_Daily_Usage_Hours
1 1          19  Female Undergraduate  Bangladesh 5.2
2 2          22  Male   Graduate       India      2.1
3 3          20  Female Undergraduate  USA        6.0
4 4          18  Male   High School    UK         3.0
5 5          21  Male   Graduate       Canada     4.5
6 6          19  Female Undergraduate  Australia  7.2
  Most_Used_Platform Affects_Academic_Performance Sleep_Hours_Per_Night
1 Instagram          Yes                          6.5
2 Twitter            No                           7.5
3 TikTok             Yes                          5.0
4 YouTube            No                           7.0
5 Facebook           Yes                          6.0
6 Instagram          Yes                          4.5
  Mental_Health_Score Relationship_Status Conflicts_Over_Social_Media
1 6                   In Relationship     3
2 8                   Single              0
3 5                   Complicated         4
4 7                   Single              1
5 6                   In Relationship     2
6 4                   Complicated         5
  Addicted_Score
1 8
2 3
3 9
4 4
5 7
6 9

Show dimentions and first 6 rows

In [17]:
myDF$Status <- ifelse(myDF$Avg_Daily_Usage_Hours > myDF$Sleep_Hours_Per_Night, "Zombie",
                 ifelse(myDF$Avg_Daily_Usage_Hours == myDF$Sleep_Hours_Per_Night, "Doom Scroll",
                        "Healthy"))
head(myDF)

  Student_ID Age Gender Academic_Level Country    Avg_Daily_Usage_Hours
1 1          19  Female Undergraduate  Bangladesh 5.2
2 2          22  Male   Graduate       India      2.1
3 3          20  Female Undergraduate  USA        6.0
4 4          18  Male   High School    UK         3.0
5 5          21  Male   Graduate       Canada     4.5
6 6          19  Female Undergraduate  Australia  7.2
  Most_Used_Platform Affects_Academic_Performance Sleep_Hours_Per_Night
1 Instagram          Yes                          6.5
2 Twitter            No                           7.5
3 TikTok             Yes                          5.0
4 YouTube            No                           7.0
5 Facebook           Yes                          6.0
6 Instagram          Yes                          4.5
  Mental_Health_Score Relationship_Status Conflicts_Over_Social_Media
1 6                   In Relationship     3
2 8                   Single              0
3 5                   Complicated         4
4 7                   Single              1
5 6                   In Relationship     2
6 4                   Complicated         5
  Addicted_Score Status
1 8              Healthy
2 3              Healthy
3 9              Zombie
4 4              Healthy
5 7              Healthy
6 9              Zombie

In [18]:
table(myDF$Status)

Doom Scroll     Healthy      Zombie
         22         536         147

Create Status column using "ifelse" and comapre the counts of each status catagory

In [22]:
max_sleep <- max(myDF$Sleep_Hours_Per_Night, na.rm = TRUE)
max_social <- max(myDF$Avg_Daily_Usage_Hours, na.rm = TRUE)

print(max_sleep)
print(max_social)

[1] 9.6
[1] 8.5

The longest recorded sleep time is 9.6 hours & longest social media time is 8.5 hours

The most common habit ratio based on status is "Healthy"

## While loops for counting down screen time and sleep time

screen_time loop

In [25]:
screen_time <- 10 
while(screen_time > 2) {
  print(paste("Screen time:", screen_time, "hours"))
  screen_time <- screen_time - 1
}

[1] "Screen time: 10 hours"
[1] "Screen time: 9 hours"
[1] "Screen time: 8 hours"
[1] "Screen time: 7 hours"
[1] "Screen time: 6 hours"
[1] "Screen time: 5 hours"
[1] "Screen time: 4 hours"
[1] "Screen time: 3 hours"

In [27]:
screen_time <- 10
sleep_time <- 2
while(sleep_time < 10) {
  print(paste("Sleep time:", sleep_time, "hours"))
  sleep_time <- sleep_time + 1
}

[1] "Sleep time: 2 hours"
[1] "Sleep time: 3 hours"
[1] "Sleep time: 4 hours"
[1] "Sleep time: 5 hours"
[1] "Sleep time: 6 hours"
[1] "Sleep time: 7 hours"
[1] "Sleep time: 8 hours"
[1] "Sleep time: 9 hours"

Differences between print(paste()) and cat():

print(paste()):
- Outputs a character vector
- Adds quotes and always prints a new line after each call
- Good for debugging

cat():
- Concatenates text without quotes
- You need to manually add newline (\n) if you want a line break
- Cleaner output for user-facing messages

In [29]:
print(paste("Screen time:", 5, "hours"))
cat("Screen time:", 5, "hours\n")

[1] "Screen time: 5 hours"
Screen time: 5 hours

In [30]:
screen_time <- 10
sleep_time <- 2

while(screen_time > 2) {
  print(paste("Screen time:", screen_time, "hours,", "Sleep time:", sleep_time, "hours"))
  
  screen_time <- screen_time - 0.5
  sleep_time <- sleep_time + 0.5
}

[1] "Screen time: 10 hours, Sleep time: 2 hours"
[1] "Screen time: 9.5 hours, Sleep time: 2.5 hours"
[1] "Screen time: 9 hours, Sleep time: 3 hours"
[1] "Screen time: 8.5 hours, Sleep time: 3.5 hours"
[1] "Screen time: 8 hours, Sleep time: 4 hours"
[1] "Screen time: 7.5 hours, Sleep time: 4.5 hours"
[1] "Screen time: 7 hours, Sleep time: 5 hours"
[1] "Screen time: 6.5 hours, Sleep time: 5.5 hours"
[1] "Screen time: 6 hours, Sleep time: 6 hours"
[1] "Screen time: 5.5 hours, Sleep time: 6.5 hours"
[1] "Screen time: 5 hours, Sleep time: 7 hours"
[1] "Screen time: 4.5 hours, Sleep time: 7.5 hours"
[1] "Screen time: 4 hours, Sleep time: 8 hours"
[1] "Screen time: 3.5 hours, Sleep time: 8.5 hours"
[1] "Screen time: 3 hours, Sleep time: 9 hours"
[1] "Screen time: 2.5 hours, Sleep time: 9.5 hours"

Final combined loop with 0.5 increments

## Looping through Star Wars characters to count non-human species

In [32]:
characters <- read.csv("/anvil/projects/tdm/data/starwars/characters.csv")
head(characters)

  id name           species        gender height weight hair_color eye_color
1 1  Luke Skywalker Human          Male   1.72    77    Blond      Blue
2 2  Leia Organa    Human          Female 1.50    49    Brown      Brown
3 3  Darth Vader    Human          Male   2.02   136    None       Yellow
4 4  Yoda           Yoda's species Male   0.66    17    White      Brown
5 5  Han Solo       Human          Male   1.80    80    Brown      Hazel
6 6  Chewbacca      Wookiee        Male   2.28   112    Brown      Blue
  skin_color year_born homeworld year_died
1 Light       19       Tatooine  34
2 Light       19       Alderaan  35
3 Pale        41       Tatooine   4
4 Green      896       Unknown    4
5 Light       29       Corellia  34
6 Brown      200       Kashyyyk  NA
  description
1 The main protagonist of the original trilogy.
2 A leader in the Rebel Alliance and twin sister of Luke Skywalker.
3 The Sith Lord formerly known as Anakin Skywalker.
4 A wise and powerful Jedi Master.
5 A smuggler turned hero in the Rebel Alliance.
6 A loyal Wookiee and co-pilot of the Millennium Falcon.

In [36]:
i <- 1
char_count <- 0
non_human_count <- 0 

while(char_count < 20) {
  
  if (characters$species[i] == "Human") {
    cat(char_count + 1, "This is a human\n") 
  } else {
    print("This is not a human")
    non_human_count <- non_human_count + 1
  }
  
  i <- i + 1
  char_count <- char_count + 1
}

cat("Number of non-human characters in first 20 is", non_human_count, "\n")

1 This is a human
2 This is a human
3 This is a human
[1] "This is not a human"
5 This is a human
[1] "This is not a human"
7 This is a human
8 This is a human
9 This is a human
10 This is a human
11 This is a human
12 This is a human
[1] "This is not a human"
14 This is a human
15 This is a human
16 This is a human
17 This is a human
18 This is a human
[1] "This is not a human"
[1] "This is not a human"
Number of non-human characters in first 20 is 5

While loop: continue until we process 20 characters

In [37]:
non_human_count_vector <- sum(characters$species[1:20] != "Human")

cat("Number of non-human characters in first 20 (no loop) is", non_human_count_vector, "\n")

Number of non-human characters in first 20 (no loop) is 5

Using vectorized operation

## Using a repeat loop to sum mental health scores

While Loop:
- Condition is checked before each iteration.
- Stops automatically when the condition becomes false.
- best used when the number of iterations is known or depends on a condition.

Repeat Loop:
- No initial condition. The loop runs atleast once.
- Must explicitly use a `break` statement to exit the loop.
- Useful when you want at least one iteration or need manual control over exiting the loop.

In [38]:
i <- 1
total_count <- 0

repeat {
  student_score <- myDF$Mental_Health_Score[i]
  
  cat("Mental health of student", i, "is", student_score, "\n")
  cat("Current mental health score is", total_count, "\n\n")
    
  total_count <- total_count + student_score
  
  if (total_count >= 100) {
    print("ALLL DONEEEEE")
    break
  }
  i <- i + 1
}

Mental health of student 1 is 6
Current mental health score is 0

Mental health of student 2 is 8
Current mental health score is 6

Mental health of student 3 is 5
Current mental health score is 14

Mental health of student 4 is 7
Current mental health score is 19

Mental health of student 5 is 6
Current mental health score is 26

Mental health of student 6 is 4
Current mental health score is 32

Mental health of student 7 is 9
Current mental health score is 36

Mental health of student 8 is 6
Current mental health score is 45

Mental health of student 9 is 7
Current mental health score is 51

Mental health of student 10 is 7
Current mental health score is 58

Mental health of student 11 is 5
Current mental health score is 65

Mental health of student 12 is 6
Current mental health score is 70

Mental health of student 13 is 8
Current mental health score is 76

Mental health of student 14 is 5
Current mental health score is 84

Mental health of student 15 is 7
Current mental health score is 89

Mental health of student 16 is 6
Current mental health score is 96

[1] "ALLL DONEEEEE"

Markdown notes and full English sentences and analysis written here.

Markdown notes and full English sentences and analysis written here.

Markdown notes and full English sentences and analysis written here.

## Pledge

By submitting this work I hereby pledge that this is my own, personal work. I've acknowledged in the designated place at the top of this file all sources that I used to complete said work, including but not limited to: online resources, books, and electronic communications. I've noted all collaboration with fellow students and/or TA's. I did not copy or plagiarize another's work.

> As a Boilermaker pursuing academic excellence, I pledge to be honest and true in all that I do. Accountable together – We are Purdue.

https://www.purdue.edu/odos/osrr/honor-pledge/